function CheckQuest()
    local Level = game.Players.LocalPlayer.Data.Level.Value
    local MyLevel = Level

    if World1 then
        if MyLevel == 1 or MyLevel <= 9 then
            LevelFarm = "Bandit [Lv. 5]"
            NameQuest = "BanditQuest1"
            QuestLv = 1
            CFrameQuestPos = CFrame.new(1060, 17, 1547)
            CFrameMon = CFrame.new(1199, 28, 1547)
        elseif MyLevel <= 14 then
            LevelFarm = "Monkey [Lv. 14]"
            NameQuest = "JungleQuest"
            QuestLv = 1
            CFrameQuestPos = CFrame.new(-1602, 36, 153)
            CFrameMon = CFrame.new(-1448, 67, 40)
        elseif MyLevel <= 29 then
            LevelFarm = "Gorilla [Lv. 20]"
            NameQuest = "JungleQuest"
            QuestLv = 2
            CFrameQuestPos = CFrame.new(-1602, 36, 153)
            CFrameMon = CFrame.new(-1237, 6, -486)
        elseif MyLevel <= 39 then
            LevelFarm = "Pirate [Lv. 35]"
            NameQuest = "BuggyQuest1"
            QuestLv = 1
            CFrameQuestPos = CFrame.new(-1141, 5, 3826)
            CFrameMon = CFrame.new(-1213, 44, 3893)
        elseif MyLevel <= 59 then
            LevelFarm = "Brute [Lv. 45]"
            NameQuest = "BuggyQuest1"
            QuestLv = 2
            CFrameQuestPos = CFrame.new(-1141, 5, 3826)
            CFrameMon = CFrame.new(-1088, 14, 4281)
        elseif MyLevel <= 74 then
            LevelFarm = "Desert Bandit [Lv. 60]"
            NameQuest = "DesertQuest"
            QuestLv = 1
            CFrameQuestPos = CFrame.new(896, 7, 4483)
            CFrameMon = CFrame.new(928, 22, 4480)
        elseif MyLevel <= 89 then
            LevelFarm = "Desert Officer [Lv. 70]"
            NameQuest = "DesertQuest"
            QuestLv = 2
            CFrameQuestPos = CFrame.new(896, 7, 4483)
            CFrameMon = CFrame.new(1572, 10, 4373)
        elseif MyLevel <= 119 then
            LevelFarm = "Snow Bandit [Lv. 90]"
            NameQuest = "SnowQuest"
            QuestLv = 1
            CFrameQuestPos = CFrame.new(1386, 87, -1297)
            CFrameMon = CFrame.new(1355, 87, -1372)
        elseif MyLevel <= 149 then
            LevelFarm = "Snowman [Lv. 100]"
            NameQuest = "SnowQuest"
            QuestLv = 2
            CFrameQuestPos = CFrame.new(1386, 87, -1297)
            CFrameMon = CFrame.new(1204, 144, -1451)
        elseif MyLevel <= 174 then
            LevelFarm = "Chief Petty Officer [Lv. 120]"
            NameQuest = "MarineQuest2"
            QuestLv = 1
            CFrameQuestPos = CFrame.new(-5033, 29, 4324)
            CFrameMon = CFrame.new(-4871, 64, 4493)
        elseif MyLevel <= 189 then
            LevelFarm = "Sky Bandit [Lv. 150]"
            NameQuest = "SkyQuest"
            QuestLv = 1
            CFrameQuestPos = CFrame.new(-4842, 717, -2623)
            CFrameMon = CFrame.new(-4951, 365, -2890)
        elseif MyLevel <= 209 then
            LevelFarm = "Dark Master [Lv. 175]"
            NameQuest = "SkyQuest"
            QuestLv = 2
            CFrameQuestPos = CFrame.new(-4842, 717, -2623)
            CFrameMon = CFrame.new(-5250, 389, -2272)
        elseif MyLevel <= 249 then
            LevelFarm = "Prisoner [Lv. 190]"
            NameQuest = "PrisonerQuest"
            QuestLv = 1
            CFrameQuestPos = CFrame.new(5308, 2, 474)
            CFrameMon = CFrame.new(5411, 96, 744)
        elseif MyLevel <= 274 then
            LevelFarm = "Dangerous Prisoner [Lv. 210]"
            NameQuest = "PrisonerQuest"
            QuestLv = 2
            CFrameQuestPos = CFrame.new(5308, 2, 474)
            CFrameMon = CFrame.new(4977, 69, 778)
        elseif MyLevel <= 299 then
            LevelFarm = "Toga Warrior [Lv. 250]"
            NameQuest = "ColosseumQuest"
            QuestLv = 1
            CFrameQuestPos = CFrame.new(-1576, 8, -2985)
            CFrameMon = CFrame.new(-1871, 39, -2917)
        elseif MyLevel <= 324 then
            LevelFarm = "Gladiator [Lv. 275]"
            NameQuest = "ColosseumQuest"
            QuestLv = 2
            CFrameQuestPos = CFrame.new(-1576, 8, -2985)
            CFrameMon = CFrame.new(-1294, 56, -3338)
        elseif MyLevel <= 374 then
            LevelFarm = "Military Soldier [Lv. 300]"
            NameQuest = "MagmaQuest"
            QuestLv = 1
            CFrameQuestPos = CFrame.new(-5313, 12, 8516)
            CFrameMon = CFrame.new(-5483, 64, 8463)
        elseif MyLevel <= 399 then
            LevelFarm = "Military Spy [Lv. 325]"
            NameQuest = "MagmaQuest"
            QuestLv = 2
            CFrameQuestPos = CFrame.new(-5313, 12, 8516)
            CFrameMon = CFrame.new(-5815, 84, 8820)
        elseif MyLevel <= 449 then
            LevelFarm = "Fishman Warrior [Lv. 375]"
            NameQuest = "FishmanQuest"
            QuestLv = 1
            CFrameQuestPos = CFrame.new(61123, 19, 1569)
            CFrameMon = CFrame.new(60844, 80, 1297)
        elseif MyLevel <= 474 then
            LevelFarm = "Fishman Commando [Lv. 400]"
            NameQuest = "FishmanQuest"
            QuestLv = 2
            CFrameQuestPos = CFrame.new(61123, 19, 1569)
            CFrameMon = CFrame.new(61891, 70, 1434)
        elseif MyLevel <= 524 then
            LevelFarm = "God's Guard [Lv. 450]"
            NameQuest = "SkyExp1Quest"
            QuestLv = 1
            CFrameQuestPos = CFrame.new(-4721, 845, -1954)
            CFrameMon = CFrame.new(-4696, 845, -1925)
        elseif MyLevel <= 549 then
            LevelFarm = "Shanda [Lv. 475]"
            NameQuest = "SkyExp1Quest"
            QuestLv = 2
            CFrameQuestPos = CFrame.new(-4721, 845, -1954)
            CFrameMon = CFrame.new(-7685, 5566, -502)
        elseif MyLevel <= 624 then
            LevelFarm = "Royal Squad [Lv. 525]"
            NameQuest = "SkyExp2Quest"
            QuestLv = 1
            CFrameQuestPos = CFrame.new(-7904, 5546, -380)
            CFrameMon = CFrame.new(-7677, 5607, -1460)
        elseif MyLevel <= 649 then
            LevelFarm = "Royal Soldier [Lv. 550]"
            NameQuest = "SkyExp2Quest"
            QuestLv = 2
            CFrameQuestPos = CFrame.new(-7904, 5546, -380)
            CFrameMon = CFrame.new(-7828, 5607, -1744)
        elseif MyLevel <= 699 then
            LevelFarm = "Galley Pirate [Lv. 625]"
            NameQuest = "FountainQuest"
            QuestLv = 1
            CFrameQuestPos = CFrame.new(5256, 38, 4050)
            CFrameMon = CFrame.new(5553, 77, 3930)
        elseif MyLevel >= 700 then
            LevelFarm = "Galley Captain [Lv. 650]"
            NameQuest = "FountainQuest"
            QuestLv = 2
            CFrameQuestPos = CFrame.new(5256, 38, 4050)
            CFrameMon = CFrame.new(5710, 77, 3986)
        end
    end
end
function CheckQuest()
    local Level = game.Players.LocalPlayer.Data.Level.Value
    local MyLevel = Level

    if World1 then
        -- [CÓDIGO DO PRIMEIRO MUNDO AQUI - você já tem completo]

    elseif World2 then
        if MyLevel == 700 or MyLevel <= 725 then
            Mon = "Raider [Lv. 700]"
            QuestName = "Area1Quest"
            QuestLevel = 1
            NameQuest = "Raider"
            CFrameMon = CFrame.new(2334, 25, 902)
            CFrameQuest = CFrame.new(2286, 15, 906)
        elseif MyLevel <= 775 then
            Mon = "Mercenary [Lv. 725]"
            QuestName = "Area1Quest"
            QuestLevel = 2
            NameQuest = "Mercenary"
            CFrameMon = CFrame.new(980, 120, 1290)
            CFrameQuest = CFrame.new(2286, 15, 906)
        elseif MyLevel <= 875 then
            Mon = "Swan Pirate [Lv. 775]"
            QuestName = "Area2Quest"
            QuestLevel = 1
            NameQuest = "Swan Pirate"
            CFrameMon = CFrame.new(878, 122, 1236)
            CFrameQuest = CFrame.new(635, 72, 917)
        elseif MyLevel <= 925 then
            Mon = "Factory Staff [Lv. 800]"
            QuestName = "Area2Quest"
            QuestLevel = 2
            NameQuest = "Factory Staff"
            CFrameMon = CFrame.new(295, 73, 1483)
            CFrameQuest = CFrame.new(635, 72, 917)
        elseif MyLevel <= 975 then
            Mon = "Marine Lieutenant [Lv. 875]"
            QuestName = "MarineQuest3"
            QuestLevel = 1
            NameQuest = "Marine Lieutenant"
            CFrameMon = CFrame.new(-2803, 73, -3036)
            CFrameQuest = CFrame.new(-2442, 73, -3216)
        elseif MyLevel <= 1025 then
            Mon = "Marine Captain [Lv. 900]"
            QuestName = "MarineQuest3"
            QuestLevel = 2
            NameQuest = "Marine Captain"
            CFrameMon = CFrame.new(-1869, 73, -3143)
            CFrameQuest = CFrame.new(-2442, 73, -3216)
        elseif MyLevel <= 1050 then
            Mon = "Zombie [Lv. 950]"
            QuestName = "ZombieQuest"
            QuestLevel = 1
            NameQuest = "Zombie"
            CFrameMon = CFrame.new(-5736, 126, -728)
            CFrameQuest = CFrame.new(-5494, 49, -795)
        elseif MyLevel <= 1100 then
            Mon = "Vampire [Lv. 975]"
            QuestName = "ZombieQuest"
            QuestLevel = 2
            NameQuest = "Vampire"
            CFrameMon = CFrame.new(-6034, 6, -1303)
            CFrameQuest = CFrame.new(-5494, 49, -795)
        elseif MyLevel <= 1150 then
            Mon = "Snow Trooper [Lv. 1000]"
            QuestName = "SnowMountainQuest"
            QuestLevel = 1
            NameQuest = "Snow Trooper"
            CFrameMon = CFrame.new(608, 402, -5372)
            CFrameQuest = CFrame.new(606, 402, -5372)
        elseif MyLevel <= 1200 then
            Mon = "Winter Warrior [Lv. 1050]"
            QuestName = "SnowMountainQuest"
            QuestLevel = 2
            NameQuest = "Winter Warrior"
            CFrameMon = CFrame.new(1155, 430, -5188)
            CFrameQuest = CFrame.new(606, 402, -5372)
        elseif MyLevel <= 1250 then
            Mon = "Lab Subordinate [Lv. 1100]"
            QuestName = "IceSideQuest"
            QuestLevel = 1
            NameQuest = "Lab Subordinate"
            CFrameMon = CFrame.new(-5782, 45, -4480)
            CFrameQuest = CFrame.new(-6060, 16, -4906)
        elseif MyLevel <= 1300 then
            Mon = "Horned Warrior [Lv. 1125]"
            QuestName = "IceSideQuest"
            QuestLevel = 2
            NameQuest = "Horned Warrior"
            CFrameMon = CFrame.new(-6292, 15, -5201)
            CFrameQuest = CFrame.new(-6060, 16, -4906)
        elseif MyLevel <= 1325 then
            Mon = "Magma Ninja [Lv. 1175]"
            QuestName = "FireSideQuest"
            QuestLevel = 1
            NameQuest = "Magma Ninja"
            CFrameMon = CFrame.new(-5428, 78, -5958)
            CFrameQuest = CFrame.new(-5449, 16, -5296)
        elseif MyLevel <= 1350 then
            Mon = "Lava Pirate [Lv. 1200]"
            QuestName = "FireSideQuest"
            QuestLevel = 2
            NameQuest = "Lava Pirate"
            CFrameMon = CFrame.new(-5799, 89, -6200)
            CFrameQuest = CFrame.new(-5449, 16, -5296)
        elseif MyLevel <= 1425 then
            Mon = "Ship Deckhand [Lv. 1250]"
            QuestName = "ShipQuest1"
            QuestLevel = 1
            NameQuest = "Ship Deckhand"
            CFrameMon = CFrame.new(1198, 126, 33031)
            CFrameQuest = CFrame.new(1038, 125, 32913)
        elseif MyLevel <= 1450 then
            Mon = "Ship Engineer [Lv. 1275]"
            QuestName = "ShipQuest1"
            QuestLevel = 2
            NameQuest = "Ship Engineer"
            CFrameMon = CFrame.new(920, 126, 32800)
            CFrameQuest = CFrame.new(1038, 125, 32913)
        elseif MyLevel <= 1475 then
            Mon = "Ship Steward [Lv. 1300]"
            QuestName = "ShipQuest2"
            QuestLevel = 1
            NameQuest = "Ship Steward"
            CFrameMon = CFrame.new(915, 126, 33075)
            CFrameQuest = CFrame.new(969, 125, 33245)
        elseif MyLevel <= 1500 then
            Mon = "Ship Officer [Lv. 1325]"
            QuestName = "ShipQuest2"
            QuestLevel = 2
            NameQuest = "Ship Officer"
            CFrameMon = CFrame.new(1043, 130, 33300)
            CFrameQuest = CFrame.new(969, 125, 33245)
        elseif MyLevel <= 1525 then
            Mon = "Arctic Warrior [Lv. 1350]"
            QuestName = "FrostQuest"
            QuestLevel = 1
            NameQuest = "Arctic Warrior"
            CFrameMon = CFrame.new(5667, 28, -6480)
            CFrameQuest = CFrame.new(5669, 28, -6761)
        elseif MyLevel <= 1575 then
            Mon = "Snow Lurker [Lv. 1375]"
            QuestName = "FrostQuest"
            QuestLevel = 2
            NameQuest = "Snow Lurker"
            CFrameMon = CFrame.new(5234, 27, -6817)
            CFrameQuest = CFrame.new(5669, 28, -6761)
        elseif MyLevel <= 1600 then
            Mon = "Sea Soldier [Lv. 1425]"
            QuestName = "ForgottenQuest"
            QuestLevel = 1
            NameQuest = "Sea Soldier"
            CFrameMon = CFrame.new(-3022, 16, -9720)
            CFrameQuest = CFrame.new(-3054, 17, -9723)
        elseif MyLevel <= 1750 then
            Mon = "Water Fighter [Lv. 1450]"
            QuestName = "ForgottenQuest"
            QuestLevel = 2
            NameQuest = "Water Fighter"
            CFrameMon = CFrame.new(-3385, 20, -10542)
            CFrameQuest = CFrame.new(-3054, 17, -9723)
        end

    elseif World3 then
        -- Vou continuar com a lógica para o Terceiro Mundo em seguida.
        -- Quer que eu continue agora ou você quer revisar essa parte primeiro?
    end
end
